### ISSUE TITLE
Code Editor Integration

### ISSUE THREAD

**Issue by JordyScript** [marktext/muya#4]
Would it be possible to make this real time preview markdown editor usable within Code Editors such as Atom or VS Code?

**Comment by fxha** [comment]
If you are looking for a desktop application you can use [Mark Text](https://github.com/marktext/marktext) that use muya or rather muya is extracted from Mark Text. Whether you can implement real time preview via extension in atom or vscode is  another question and you should open an issue in the respective projects (and/or read there documentation) but I don't think so because these are text editors.
